"""keys.py — device key material for the E2EE protocol (X3DH + Double Ratchet).

A device holds two kinds of identity:

  * an Ed25519 *auth identity* — the public half is registered with the
    backend (``ik_public``) and used for proof-of-possession plus signing the
    device's signed prekey; and
  * an X25519 *X3DH identity* — participates in the X3DH shared-secret
    computation (identity keys in X3DH must be usable for Diffie-Hellman).

These live side by side: Ed25519 authenticates (signatures), X25519 agrees
(keys). The signed prekey and one-time prekeys are X25519 keys. The bundle
served by ``/keys/bundle`` carries the auth identity (so the SPK signature can
be verified), the X3DH identity, and the signed prekey with its signature.

All key material is 32 bytes (256-bit), matching the 64-hex-string contract of
:mod:`server.routes.keys`.
"""

from __future__ import annotations

from dataclasses import dataclass

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey,
    X25519PublicKey,
)

# Domain-separator: the SPK signature covers exactly this bound context so a
# signature cannot be replayed against a different key or a different app.
SPK_SIGN_CONTEXT = b"secure-messaging-signed-prekey-v1"

KEY_SIZE = 32


def _priv_bytes(priv: X25519PrivateKey) -> bytes:
    return priv.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )


def _pub_bytes(pub: X25519PublicKey) -> bytes:
    return pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )


def ed25519_public_bytes(pub: Ed25519PublicKey) -> bytes:
    return pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )


def ed25519_public_from_bytes(raw: bytes) -> Ed25519PublicKey:
    if len(raw) != KEY_SIZE:
        raise ValueError("Ed25519 public key must be 32 bytes")
    return Ed25519PublicKey.from_public_bytes(raw)


def x25519_private_from_bytes(raw: bytes) -> X25519PrivateKey:
    if len(raw) != KEY_SIZE:
        raise ValueError("X25519 private key must be 32 bytes")
    return X25519PrivateKey.from_private_bytes(raw)


def x25519_public_from_bytes(raw: bytes) -> X25519PublicKey:
    if len(raw) != KEY_SIZE:
        raise ValueError("X25519 public key must be 32 bytes")
    return X25519PublicKey.from_public_bytes(raw)


@dataclass
class DeviceKeys:
    """Private key material that stays on the device."""

    auth_private: Ed25519PrivateKey
    xdh_private: X25519PrivateKey

    # Prekeys are generated by the device; the private halves are kept.
    spk_private: X25519PrivateKey
    opk_privates: tuple[X25519PrivateKey, ...] = ()


@dataclass
class KeyBundle:
    """The public material served to peers (mirrors the server bundle)."""

    ik_public: bytes  # Ed25519 auth identity (32 bytes)
    xdh_public: bytes  # X25519 X3DH identity (32 bytes)
    spk_public: bytes  # X25519 signed prekey (32 bytes)
    spk_signature: bytes  # Ed25519 sig over SPK_SIGN_CONTEXT || spk_public
    opk_publics: tuple[bytes, ...]  # X25519 one-time prekeys

    def public_hex(self) -> dict[str, object]:
        return {
            "ik_public": self.ik_public.hex(),
            "xdh_public": self.xdh_public.hex(),
            "spk_public": self.spk_public.hex(),
            "spk_signature": self.spk_signature.hex(),
            "opk_publics": [key.hex() for key in self.opk_publics],
        }


def generate_device_keys(
    *,
    opk_count: int = 0,
) -> DeviceKeys:
    """Create a fresh device identity and ``opk_count`` one-time prekeys."""
    if opk_count < 0:
        raise ValueError("opk_count must be >= 0")
    return DeviceKeys(
        auth_private=Ed25519PrivateKey.generate(),
        xdh_private=X25519PrivateKey.generate(),
        spk_private=X25519PrivateKey.generate(),
        opk_privates=tuple(
            X25519PrivateKey.generate() for _ in range(opk_count)
        ),
    )


def build_key_bundle(device: DeviceKeys) -> KeyBundle:
    """Derive the public bundle from a :class:`DeviceKeys`."""
    spk_public = _pub_bytes(device.spk_private.public_key())
    signature = device.auth_private.sign(SPK_SIGN_CONTEXT + spk_public)
    return KeyBundle(
        ik_public=ed25519_public_bytes(device.auth_private.public_key()),
        xdh_public=_pub_bytes(device.xdh_private.public_key()),
        spk_public=spk_public,
        spk_signature=signature,
        opk_publics=tuple(
            _pub_bytes(priv.public_key()) for priv in device.opk_privates
        ),
    )


def verify_signed_prekey(
    ik_public: bytes,
    spk_public: bytes,
    spk_signature: bytes,
) -> bool:
    """Verify the SPK signature against the peer's Ed25519 auth identity."""
    try:
        ed25519_public_from_bytes(ik_public).verify(
            spk_signature, SPK_SIGN_CONTEXT + spk_public
        )
        return True
    except Exception:
        return False


def x25519_public_raw(priv: X25519PrivateKey) -> bytes:
    return _pub_bytes(priv.public_key())


def x25519_private_raw(priv: X25519PrivateKey) -> bytes:
    return _priv_bytes(priv)


def dh(priv: X25519PrivateKey, peer_public: bytes) -> bytes:
    """Raw X25519 shared secret with a peer's 32-byte public key."""
    peer = x25519_public_from_bytes(peer_public)
    return priv.exchange(peer)
